tarnijakataloogid_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 1
      sslmode: require
      connect_timeout: 60
      keepalives: 1
      keepalives_idle: 10
      keepalives_interval: 5
      keepalives_count: 10
